server.port=8080
server.servlet.context-path=/api
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:studentdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# workaround to use open ai compatible gemini models
spring.ai.openai.api-key=${GEMINI_API_KEY:}
spring.ai.openai.chat.base-url=https://generativelanguage.googleapis.com/v1beta/openai
spring.ai.openai.chat.completions-path=/chat/completions
spring.ai.openai.chat.options.model=gemini-3.1-flash-lite-preview
#spring.ai.vertex.ai.gemini.api-key=${GEMINI_API_KEY:}
#spring.ai.gemini.chat.options.model=gemini-2.0-flash

#actuator variables
management.endpoints.web.exposure.include=mappings